### ISSUE TITLE
MongoDB: Not processing Recurrence field

### ISSUE THREAD

**Issue by dkomarov** [567WebSystems/project2alpha#13]
Our database functionality from the latest pull request does store the event data into the database. From the form or Postman, all fields are being stored except for the Recurrence value. If you look closely, Mongo is not storing the Recurrence: 

<img width="1079" alt="data_transfer" src="https://user-images.githubusercontent.com/21226482/75479590-6805c900-5965-11ea-8111-0421485b4295.png">

This can also be confirmed via the browser and/or console:

<img width="848" alt="Screen Shot 2020-02-27 at 1 29 41 PM" src="https://user-images.githubusercontent.com/21226482/75479619-748a2180-5965-11ea-8908-6a22233b896b.png">

If any ideas on how to store this field, or how to resolve, please do post them here. Thank you.

**Comment by jtron82** [comment]
Change 'reccurence' to 'recurrence' so that it is logged into the DB.
![image](https://user-images.githubusercontent.com/31261926/75483214-fe3ced80-596b-11ea-8308-54aada2f3636.png)

After changes, data is properly sent and stored in DB.
![image](https://user-images.githubusercontent.com/31261926/75483256-1b71bc00-596c-11ea-88ba-95bead26f002.png)

**Comment by dkomarov** [comment]
Yes, this issue was resolved by the solution provided by jtron82. The db is now transferring all data as shown in his image. I have opened a new pull request for review here: 

https://github.com/567WebSystems/project2alpha/pull/14
