### ISSUE TITLE
On login, id# is showing up instead of username

### ISSUE THREAD

**Issue by dkomarov** [567WebSystems/project2alpha#22]
Immediately after logging in, this is what is observed:

<img width="939" alt="Screen Shot 2020-03-14 at 6 02 19 PM" src="https://user-images.githubusercontent.com/21226482/76691929-0ceafc00-661e-11ea-9e3d-8861da86a154.png">

Note that this issue is _not_ resolved after refreshing the page. However, it is resolved once an event is submitted, like so:

***pressed submit***
<img width="693" alt="iss1pt2" src="https://user-images.githubusercontent.com/21226482/76691949-3a37aa00-661e-11ea-870c-489024c34ae4.png">

**Comment by jtron82** [comment]
when you press on view appointments or refresh the new event shows because in the code, you are looking for a currentEvent but when there isn't one it will create one using current users event information giving you Event Stored. so when you refresh page it will look for currentEvent and then display on the page and logging Event already exists

**Comment by dkomarov** [comment]
to show username, it should read:
res.render(‘appointment’,{user:req.user.userName});

here is the commit:
https://github.com/567WebSystems/project2alpha/commit/c3f351efb4754cf9893c4bb3af6467568363b8fa
